name: Auto Deploy Project When Push Main Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./client-docs

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Deploy
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.API_KEY_GITHUB }}
          deploy-branch: gh-pages
          build_dir: content
