name: Auto Deploy Project When Push Main Branch
  on:
    push:
      branches:
        - main
​
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: cd dir
      run: cd client-docs
    - name: Checkout
      uses: actions/checkout@v1
      
​
    - name: Deploy
      uses: enriikke/gatsby-gh-pages-action@v2
      with:
        access-token: ${{ secrets.API_KEY_GITHUB }}
        deploy-branch: gh-pages
